### ISSUE TITLE
[Distros] Gentoo

### ISSUE THREAD

**Issue by aarroz** [egee-irl/egeeio#14]
Gentoo is a highly customizable, "rolling release" distro similar to Arch or OpenSUSE tumbleweed. Updates occur weekly for the Gentoo packages. But Gentoo is not close to user friendly.
This distro is meant for use by those who need to optimize their machine down to the kernel level for the most efficiency. While the pros of this is having a system optimized for the machine hosting it, the cons are the steps required to optimize this system. Gentoo's extreme customizability is confusing for beginning linux users.
Unlike Debian's aptitude or Arch's AUR, Gentoo has the emerge package system. Which is efficient in finding packages, but requires packages to be specificed in order to merge and use the packages. And if the kernel does not support it, you have to reconfigue and recompile it to take advantage of new packages or features.
Gentoo is high customizable to your liking, but requires a lot of time in order to install and maintain your gentoo system.

I wouldn't recommend Gentoo for the average user, unless they are willing to invest a lot of time in learning how to use terminal utilities and kernel configs. Gentoo is a linux distro for the user that requires a highly optimized system for their specific use.

**Comment by egee-irl** [comment]
Merged this into the other Gentoo feature
