### ISSUE TITLE
Guarantee 98% uptime

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#15]
The server innards have been migrated to a new chassis but we are still seeing weird hicups in availability. I suspect we can solve these issues by simply moving the web server itself to a new physical location, instead of sharing the same physical resources as the game server.

**Comment by egee-irl** [comment]
Moving the physical location of the server has been completed, but network issues continue to occur. Suggest some kind of wifi extended or hardline.

**Comment by GhostSquad57** [comment]
Is running a long Ethernet cable totally out of the question?

**Comment by egee-irl** [comment]
Web server uses it's own router now. Hopefully that should solve most of the issues.
