### ISSUE TITLE
Serve the website using Nginx

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#21]
https://ember-cli.com/user-guide/#deployments

**Comment by GhostSquad57** [comment]
http://iamstef.net/ember-app-kit/guides/deployment.html

Has a section on deploying ember apps via nginx.

**Comment by GhostSquad57** [comment]
nginx is *really* simple, lightweight, and flexible.

**Comment by MattSturgeon** [comment]
It may be worth highlighting why you feel niginx is needed. While I also agree niginx is a nice, simple, web server, ember is built on nodejs which it's self can be a flexible web server.

What is to be gained from using niginx that node and ember don't provide out of the box or with some minor tweaks?

**Comment by egee-irl** [comment]
The super douper light weight Ember web server isn't designed for production environments (which is effectively what Egee.io is). Niginx offers a couple things such as DDOS protection and redirection for error codes.

**Comment by GhostSquad57** [comment]
Yeah egee weren't you having issues with Ember just crashing out of nowhere?

**Comment by egee-irl** [comment]
I'm not sure what @GhostSquad57 is smoking but I've never had ember abruptly crash out on me.

**Comment by egee-irl** [comment]
THIS ISSUE IS FUCKING DONE SON. THANKS ghostsquad57

**Comment by GhostSquad57** [comment]
Egee:

>  How do I do this

Me: 

> Move the root of the server to nginx's root defined in default and run nginx

Egee: 

> Oh, it works

Issue closed
