### ISSUE TITLE
SEO Egee.io to make it searchable in search engines

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#26]

**Comment by GhostSquad57** [comment]
Hey Egee, just out of curiosity, what methods did you use to SEO the site? Did you use robot.txt and a sitemap?

**Comment by egee-irl** [comment]
No actually I closed this item because it is mostly irrelevant. The vast majority of referrers come from direct links and there's not good use case for searching for "Egee" right now. There's a huge amount of competition for the search term "Egee" and it's not worth it.

**Comment by MattSturgeon** [comment]
You are a first page result on google, so that's something. Looks like the main result is an old project that later became the [EGI Foundation](https://en.wikipedia.org/wiki/European_Grid_Infrastructure)

**Comment by StripedMonkey** [comment]
Your Youtube Channel is at the very bottom of the first page so thats
definitely something (At least for me)
