### ISSUE TITLE
Sudoshred Bio

### ISSUE THREAD

**Issue by sudoshred** [egee-irl/egeeio#37]
Sudoshred is a Linux Sys Admin and fully believes that Linux and open source can change the world.

He streams Linux native games and distro releases on Twitch.  He started his Twitch streaming in an effort to dispell the myth that Linux has no games and to educate people on Linux.

His goal is to help people move to Linux and grow Linux.

**Comment by egee-irl** [comment]
Also need an avatar at least 512x512 for your profile

**Comment by sudoshred** [comment]
I don't really have an avatar, so how does this do:
http://ih1.redbubble.net/image.198448355.4265/flat,800x800,075,t.jpg

**Comment by sudoshred** [comment]
Social Media
https://www.twitch.tv/sudoshred
https://twitter.com/sudoshred
