### ISSUE TITLE
Quakeworld - community server bio

### ISSUE THREAD

**Issue by GhostSquad57** [egee-irl/egeeio#38]
GhostSquad57 from the Egee.io community runs a Quakeworld server over at (ip):28501

The recommended client for joining the server is [nQuake](http://nquake.com/) which runs on Linux, Mac OS X, and Windows. Any Quakeworld compatible client *should* connect to the server without any issues, but nQuake is **strongly** recommended.

Some Information about the server:
* Hardware: the server uses an Intel i5-3550 at 3.3GHz and 16GBs of Ballistix Sport UDIMM Memory. For storage, the server uses a 250GB Samsung EVO SSD Premier SP600. The server is also equipped with an Intel Pro/1000 Dual Gigabit LAN NIC.
* Software used to host the server: the server uses the Quakeworld client [nQuakesv](http://nquake.com/)
* Mods: the server uses [KTX](https://github.com/deurk/ktx) and [QWFWD](http://wiki.quakeworld.nu/QWfwd)
* Uptime: varies; usually %80 uptime
* Gamemode: Free-For-All (FFA)
* Maps: the default map is `dm4`. The map rotation currently consists of `dm4`, `dm6`, `hate`, `head-shot`, `efdm10`, and `genocide`
* Maxplayers: currently the `maxplayers` is set to `8`

Connecting to the server:

1. launch `nquake`
2. open the ingame console with `~`
3. type in `connect ip:28501`
4. ???
5. Profit!

Feedback is welcomed:
If you think a different gamemode would be better, or maybe you think the maxplayers should be higher, then contact me on the Egee.io Discord and I'll be glad to make the changes.

**Comment by egee-irl** [comment]
I still need your ip..
