### ISSUE TITLE
Project Zomboid - community server bio

### ISSUE THREAD

**Issue by GhostSquad57** [egee-irl/egeeio#39]
GhostSquad57 from the Egee.io community runs a Project Zomboid server over at: (ip):16261

* Hardware: the server uses an Intel i5-3550 at 3.3GHz and 16GBs of Ballistix Sport UDIMM Memory. For storage, the server uses a 250GB Samsung 850 EVO SSD. The server is also equipped with an Intel Pro/1000 Dual Gigabit LAN NIC.
* Software used to host the server: the server is SteamVAC secured; unfortunetly people with the GOG version cannot connect
* Mods: [Phoenix](https://steamcommunity.com/sharedfiles/filedetails/?id=514427485), [ORMtnMan's Real Gun Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=514618604), [OGRM Silencers](https://steamcommunity.com/sharedfiles/filedetails/?id=640674707), [Hydrocraft](https://steamcommunity.com/sharedfiles/filedetails/?id=498441420), [More Zombie Loot](https://steamcommunity.com/sharedfiles/filedetails/?id=498342776), 
* Uptime: varies; usually %80
* Gamemode: PvE and PVP
* SpawnItems: the player spawns with these items: Disinfectant, Bandage, Pills, Hunting Knife, 3x Bullets 9mm, Pistol, Hiking Bag, and a Watermelon.
* Map: Muldraugh, KY & Phoenix
* Maxplayers: currently the maxplayers is set to 12
* Ping Limit: people with ping over 250 will be kicked
* Safehouses: safehouses are enabled
* Sandbox Vars: XP is multiplied by 2. Loot respawns and there's higher chances of good loot. Zombie vars have also been changed to make them easier to combat and avoid

Connecting to the server:
1. you need the Steam version of Project Zomboid
2. from the main menu select `join` in the bottom left
3. make sure you're on the `FAVORITES` tab
4. fill the right-hand side as follows:
* Favorite Name: set whatever you want here
* IP: MY_IPADDRESS_EGEE_READ_THIS!
* Local IP: leave blank
* Port: 16261
* Server Password: leave blank
* Description: set this to whatever
* Account Username: set this to what you want your character name to be
* Account Password: if you type in a password here, your name will be reserved and you'll have to use the password everytime you want to connect with that user
* Click add and voilà! the server should now be added to your favorites

After you've filled everything out and added the server to your favorites, simply click on the server and click `JOIN SERVER` on the bottom.

I'm looking for feedback on the Zomboid server: if there are any mods you'd like to see added, please contact me over at the egee.io Discord and I'll get right on it.

**Comment by egee-irl** [comment]
I need yo IP

**Comment by GhostSquad57** [comment]
I posted it in the Discord

**Comment by GhostSquad57** [comment]
So I've decided against making the server PvP.

I think co-op would be much better
