### ISSUE TITLE
Replace Minecraft picture with one from the community

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#50]
This is a fantastic picture - https://images-2.discordapp.net/.eJwNyFEOgyAMANC78G9pi0LxMgtBgiYqRLqvZXff3uf7mPdzmtXsqn2s1m7HyO3ZYGh7Ui1QW6tnSf0YkNtlk2rK-1VuHZbEhRl99OI4IhGjZfbBhUVwjhxIUP6F5CeME4UXCRADL9Dvar4_iukjqw.1rWMYhpKaY4gKhK3OC_VIfpVsQ0

**Comment by MattSturgeon** [comment]
BTW you can use `![alt text](image url)` to have the image be dispalyed inline; like so:

![Cool screenshot of spawn](https://images-2.discordapp.net/.eJwNyFEOgyAMANC78G9pi0LxMgtBgiYqRLqvZXff3uf7mPdzmtXsqn2s1m7HyO3ZYGh7Ui1QW6tnSf0YkNtlk2rK-1VuHZbEhRl99OI4IhGjZfbBhUVwjhxIUP6F5CeME4UXCRADL9Dvar4_iukjqw.1rWMYhpKaY4gKhK3OC_VIfpVsQ0)


Feel free to delete this if you edit your comment :)
