### ISSUE TITLE
My Blurb

### ISSUE THREAD

**Issue by heavyelement** [egee-irl/egeeio#59]
![Image to use](https://cdn.discordapp.com/attachments/225933419803181057/232675115257561089/terrible-mistake.png)

The Linux Gamer 

Gardiner (aka The Linux Gamer) is a YouTube video game critic, comedian, and musician. He dabbles in web design, art & graphic work, and writing as well.

His goal is simple: create a YouTube channel anyone can enjoy! You can subscribe to his channel and follow him on Twitter.

**Comment by egee-irl** [comment]
So your icon on the site will be a square of your face, kind of like how Ghost has his. Is that cool with you?

**Comment by heavyelement** [comment]
Sounds good to me, Egee.

**Comment by MattSturgeon** [comment]
Looks kinda like Dimitri from Hardwarecanucks in that photo!
