### ISSUE TITLE
on Community sub page, you can not dismiss a popup by clicking elsewhere

### ISSUE THREAD

**Issue by mralext20** [egee-irl/egeeio#61]
example: click on Ghost's blurb. 

the only way to close the blurb is now to hit escape.

this is not very friendly to mouse driven enviroments.

**Comment by egee-irl** [comment]
I spent about two hours looking into ways around this before implementing it the way it is. This might be the way the <dialog> element is designed. The solution is probably to use JavaScript instead of html for dialogs.

**Comment by egee-irl** [comment]
The underlying bug is fixed. There might be new issues but this problem no longer exists
