### ISSUE TITLE
Persona submission

### ISSUE THREAD

**Issue by Zawaken** [egee-irl/egeeio#64]
![robiiin egee io](https://cloud.githubusercontent.com/assets/22756311/19254593/826a2774-8f55-11e6-9abb-374c58de4aba.jpeg)

Robin[Zawaken] is a recently ascended full time Linux user. He hopes that in the next few years Linux-usage will be at par with the competitors. He uses most of his time to derp around in discord, so you'll probably catch him in the Voice/Text-channels or Ingame on steam.

Steam: http://steamcommunity.com/id/Zawaken/
Twitter: https://twitter.com/Zawakeen

**Comment by egee-irl** [comment]
Looks good but I'd like to avoid putting face pics on the site. Ghost gets away with it cos he's old school and Gardiner _might_ get away with it, but I'd like to avoid it.

**Comment by Zawaken** [comment]
Ok so, a anime picture wont work prolly, I'll make something in photoshop/krita :)

**Comment by Zawaken** [comment]
![zawaken egee](https://cloud.githubusercontent.com/assets/22756311/19257214/18c96ad2-8f6e-11e6-8cdc-0920e9f48ed0.jpg)

Would this work better Egee? :)

**Comment by egee-irl** [comment]
Yup. Keep an eye out next weekend for it

**Comment by Zawaken** [comment]
Closing it now :+1:
