### ISSUE TITLE
Rightmost profile link in a blurb starts highlighted

### ISSUE THREAD

**Issue by skwerlman** [egee-irl/egeeio#65]
![image](https://cloud.githubusercontent.com/assets/6954107/19344979/67172eca-910a-11e6-9f92-1a15d7b90bd8.png)

Also, the highlight for each link is too low.

(I wish I had any idea how to CSS so I could fix it instead of just pointing it out...)

**Comment by egee-irl** [comment]
Yup, noticed this too. I might just turn the highlight off.

I'm looking at alternatives to this dialog modal so the whole thing might get restyled and this won't be a problem anymore

**Comment by egee-irl** [comment]
Fixed
