### ISSUE TITLE
Investigate using CDN instead of self-hosting assets

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#68]
Self hosting becomes expensive when IO and CPU is a commodity (such as on a Pi)

**Comment by MattSturgeon** [comment]
Could use [cloudflare](https://www.cloudflare.com/plans/), although I've heard of a number of [issues](https://blog.torproject.org/blog/trouble-cloudflare) of them permanently blocking "suspicious" IPs such as Tor end nodes.

**Comment by GhostSquad57** [comment]
There are [issues with using Cloudflare](https://www.reviewhell.com/blog/cloudflare-makes-websites-slower/) that you have to take into consideration

**Comment by MattSturgeon** [comment]
Yeah thinking about it I don't know why I suggested them, maybe I was secretly warning against them

**Comment by GhostSquad57** [comment]
If you're concerned with price egee, you could use: http://www.cdncalc.com/ to find an affordable one. But TBH, all CDNs are kind of pricey.

**Comment by egee-irl** [comment]
It's not bandwidth I'm trying to keep low, it's IO and CPU usage. Maybe I'll just make the game server the CDN.

**Comment by GhostSquad57** [comment]
AH OK, I see now. Really, any CDN is fine if you're not using much bandwidth and only using it for assets.

**Comment by egee-irl** [comment]
Closing this issue because I think a better strategy would be trimming the JS and minifiying it.
