### ISSUE TITLE
[FEATURE] Page for content (i.e., videos, articles, news, etc.)

### ISSUE THREAD

**Issue by GhostSquad57** [egee-irl/egeeio#7]
Is egee.io going to stay as a sort of static homepage, or is there plans to expand and add content?

I think we (me, Egee, and TheLinuxGamer) should write our own articles for the site, post videos from our YT channels, and even share news articles.

I was also thinking of hosting a podcast where we talk about the latest happenings in the Linux world.

Let me know what you all think!

**Comment by egee-irl** [comment]
I've been thinking eventually having a blog similar to the way Gaming On Linux does theirs.

**Comment by egee-irl** [comment]
I edited the title to reflect the future addition of a Ghost.io blog which will integrate seamlessly into the site and provide the requested feature.
