### ISSUE TITLE
Setup HTTPS with Let's Encrypt?

### ISSUE THREAD

**Issue by GhostSquad57** [egee-irl/egeeio#70]
Here's an article which explains how to do this with Let's Encrypt: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

Pretty simple.

**Comment by StripedMonkey** [comment]
Heh, I remember asking if there was any particular reason why he *didn't* have
this set up and the simple reason why was because it doesn't need to. There
is absolutely no private information sent or received from the website.

**Comment by GhostSquad57** [comment]
TBH, this is just something for Egee to ponder about.

Even if egee.io doesn't deal with sensitive information, there are still advantages to using HTTPS (preventing Man-in-the-middle attacks for one).

One big disadvantage to setting up HTTPS is that it adds a bit more overhead.

Ultimately, this is @egee-irl's decision

**Comment by egee-irl** [comment]
Ehh there's a stigma around not having https and there's little to no value in not having it. The main thing I'm concerned with is keeping the certs up to date.

**Comment by GhostSquad57** [comment]
The article I linked has a crontab that auto renews certs.

**Comment by GhostSquad57** [comment]
Someone else can help Egee with this, considering I'm not longer a member of Egee.io
