### ISSUE TITLE
Minecraft server blurb references a discord channel that no longer exists

### ISSUE THREAD

**Issue by StripedMonkey** [egee-irl/egeeio#72]
The minecraft server blurb asks to contact me through the "Minecraft" channel on discord which no longer exists.

**Comment by egee-irl** [comment]
Such an easy fix, you could do it! - https://github.com/egee-irl/egeeio/blob/master/app/templates/partials/games-tab/servers/minecraft/index.hbs

See that cute little edit button right there at the top right? Go for it!

**Comment by StripedMonkey** [comment]
lol, I'm *super* lazy :p I might do it... Maybe tomorrow

**Comment by StripedMonkey** [comment]
Or maybe the next...

**Comment by StripedMonkey** [comment]
Or the next day
