### ISSUE TITLE
Add Gentoo to distro list

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/egeeio#8]
Gentoo is a good, legit distro and ought to be added to the distro list.

Sabayon Linux would be listed as a derivative

**Comment by GhostSquad57** [comment]
I would classify Gentoo as a somewhat difficult distro to use (probably in between Arch and Debian in terms of difficulty). And if I'm not mistaken, Gentoo is very serious when it comes to adhering to the GPL standards, so I would also classify Gentoo as being more "open" than Debian. I look in Gentoo when I have some free time.

**Comment by egee-irl** [comment]
@GhostSquad57 Sounds like we got ourselves a volunteer

**Comment by GhostSquad57** [comment]
I'll help write a piece about it.

Has anyone here ever used Gentoo?

**Comment by egee-irl** [comment]
From the amazing Arroz (Rice):

> Gentoo is a highly customizable, "rolling release" distro similar to Arch or OpenSUSE tumbleweed. Updates occur weekly for the Gentoo packages. But Gentoo is not close to user friendly.
This distro is meant for use by those who need to optimize their machine down to the kernel level for the most efficiency. While the pros of this is having a system optimized for the machine hosting it, the cons are the steps required to optimize this system. Gentoo's extreme customizability is confusing for beginning linux users.
Unlike Debian's aptitude or Arch's AUR, Gentoo has the emerge package system. Which is efficient in finding packages, but requires packages to be specificed in order to merge and use the packages. And if the kernel does not support it, you have to reconfigue and recompile it to take advantage of new packages or features.
Gentoo is high customizable to your liking, but requires a lot of time in order to install and maintain your gentoo system.

I wouldn't recommend Gentoo for the average user, unless they are willing to invest a lot of time in learning how to use terminal utilities and kernel configs. Gentoo is a linux distro for the user that requires a highly optimized system for their specific use.
